
comment: |
  As described in the issue template, issues missing the required info will be closed.
  Please open a new issue, fill in as much as you can, and do not remove anything in the template.
issueConfigs:
- content:
  - "Describe the issue"
  - "Config YAML"
  - "HA and/or Browser Error"
  - "Versions and Browser"
- content:
  - "feature request"
  - "Describe the solution"
caseInsensitive: true
