site_name: Compact Custom Header
site_description: "Customize the header and add enhancements to Lovelace. Features: kiosk mode, conditional header styling, per user/device views, swiping between views on mobile, and more."
repo_url: https://github.com/maykar/compact-custom-header
site_url: https://maykar.github.io/compact-custom-header
plugins: []
markdown_extensions:
    - toc:
        permalink: true
        baselevel: 1
nav:
  - Home: index.md
  - Configuration:
      - Main Config: Main-Config-Options.md
      - Swipe Navigation: Swipe-Navigation.md
      - Exception: Exception-Config.md
      - Styling: Styling-Config.md
      - Conditional Styling: Conditional-Styling-Config.md
      - Conditional Styling Templates: Conditional-Styling-Templates.md
  - Troubleshooting: Troubleshooting.md
  - Issues: Issues.md
theme:
    name: mkdocs
    include_sidebar: false
    highlightjs: true
    hljs_languages:
        - yaml