site_name: Compact Custom Header
site_description: "Customize the header and add enhancements to Lovelace. Features: kiosk mode, conditional header styling, per user/device views, swiping between views on mobile, and more."
repo_url: https://github.com/maykar/compact-custom-header
site_url: https://maykar.github.io/compact-custom-header
plugins: []
markdown_extensions:
    - toc:
        permalink: true
        baselevel: 1
nav:
  - Home: index.md
  - Installation: Installation.md
  - Main Config:
      - Main Config Options: Main-Config-Options.md
      - Swipe Nav Config: Swipe-Navigation.md
      - Exception Config: Exception-Config.md
      - Styling Config: Styling-Config.md
      - Conditional Styling Config: Conditional-Styling-Config.md
      - Conditional Styling Templates: Conditional-Styling-Templates.md
  - Troubleshooting: Troubleshooting.md
  - Issues: https://github.com/maykar/compact-custom-header/issues
